MVCDemo/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using MVCDemo.Areas.HelpPage.ModelDescriptions;
using MVCDemo.Areas.HelpPage.Models;

namespace MVCDemo.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

MVCDemo/Controllers/API/RehearsalsController.cs
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web.Http;
using System.Web.Http.Description;
using BGoodMusic.EFDAL;
using BGoodMusic.Models;

namespace MVCDemo.Controllers.API
{
    public class RehearsalsController : ApiController
    {
        private BGoodMusicDBContext db = new BGoodMusicDBContext();

        // GET: api/Rehearsals
        public IQueryable<Rehearsal> GetRehearsals()
        {
            return db.Rehearsals;
        }

        // GET: api/Rehearsals/5
        [ResponseType(typeof(Rehearsal))]
        public IHttpActionResult GetRehearsal(int id)
        {
            Rehearsal rehearsal = db.Rehearsals.Find(id);
            if (rehearsal == null)
            {
                return NotFound();
            }

            return Ok(rehearsal);
        }

        // PUT: api/Rehearsals/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutRehearsal(int id, Rehearsal rehearsal)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != rehearsal.Id)
            {
                return BadRequest();
            }

            db.Entry(rehearsal).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!RehearsalExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Rehearsals
        [ResponseType(typeof(Rehearsal))]
        public IHttpActionResult PostRehearsal(Rehearsal rehearsal)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Rehearsals.Add(rehearsal);
            db.SaveChanges();

            return CreatedAtRoute("DefaultApi", new { id = rehearsal.Id }, rehearsal);
        }

        // DELETE: api/Rehearsals/5
        [ResponseType(typeof(Rehearsal))]
        public IHttpActionResult DeleteRehearsal(int id)
        {
            Rehearsal rehearsal = db.Rehearsals.Find(id);
            if (rehearsal == null)
            {
                return NotFound();
            }

            db.Rehearsals.Remove(rehearsal);
            db.SaveChanges();

            return Ok(rehearsal);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool RehearsalExists(int id)
        {
            return db.Rehearsals.Count(e => e.Id == id) > 0;
        }
    }
}

MVCDemo/Controllers/MusicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using MVCDemo.ViewModels.Music;
using BGoodMusic.EFDAL.Interfaces;
using BGoodMusic.Models;

namespace MVCDemo.Controllers
{
    [RoutePrefix("demo/music")]
    [Route("{action}")]
    public class MusicController : Controller
    {
        // GET: Music
        [Route]
        [Route("index")]
        public ActionResult Index()
        {
            IBGoodMusicRepository repo = new BGoodMusic.EFDAL.BGoodMusicDBContext();
            List<RehearsalListItem> itemList = new List<RehearsalListItem>();
            foreach(var r in repo.GetRehearsals().ToList())
            {
                itemList.Add(new RehearsalListItem
                    {
                        Id = r.Id,
                        Date = r.Date,
                        Duration = r.Duration,
                        Location = r.Location,
                        Time = r.Time
                    });
            }
            return View(itemList);
        }

        [Route("rehearsals")]
        public ActionResult Rehearsals()
        {
            StringBuilder msg = new StringBuilder();
            RehearsalViewModel model = new RehearsalViewModel();
            ViewBag.Message = msg.ToString();
            return View(model);
        }
    }
}

MVCDemo/Views/Shared/_Footer.cshtml
<footer>
    <p>&copy; @DateTime.Now.Year - Robert Goodearl</p>
</footer>

MVCDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html data-ng-csp>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - MVC/Ng Demo</title>
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @RenderSection("headend", required: false)
</head>
<body>
    <div id="lo-appdata" data-appdata='{ "rootPath": "@Url.Content("~")"}' class="hidden"></div>
    @Html.Partial("~/Views/Shared/_TopNav.cshtml")
    <div class="container body-content">
        @RenderBody()
        <hr />
        @Html.Partial("~/Views/Shared/_Footer.cshtml")
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/angular.js"></script>
    <script src="~/Scripts/angular-route.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MVCDemo/Views/Shared/_TopNav.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("MVC Ng Demo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                @*<li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>*@
                <li>@Html.ActionLink("Rehearsals (MVC)", "Index", "Music")</li>
                <li>@Html.ActionLink("Rehearsals (Ng)", "Rehearsals", "Music")</li>
            </ul>
        </div>
    </div>
</div>